name: kostock
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2  # 아이콘 생성기 추가
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_img.png"  # 변경할 아이콘 경로

flutter:
  assets:
    - assets/logo.png
    - assets/signup_logo.png
    - assets/news_image.png
    - assets/news_image_1.png
    - assets/news_image_2.png
    - assets/news_image_3.png
  uses-material-design: true
