// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_UWj_SeL74JTNcmzY93ZrnToZU3e_PGs',
    appId: '1:754296171774:android:af470b279c508697c3c9af',
    messagingSenderId: '754296171774',
    projectId: 'kostock-project',
    storageBucket: 'kostock-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOqMri41XSQtdPCG-2H31P1RpB63fV0X8',
    appId: '1:754296171774:ios:6510b69659e26356c3c9af',
    messagingSenderId: '754296171774',
    projectId: 'kostock-project',
    storageBucket: 'kostock-project.appspot.com',
    iosBundleId: 'com.example.kostock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOqMri41XSQtdPCG-2H31P1RpB63fV0X8',
    appId: '1:754296171774:ios:6510b69659e26356c3c9af',
    messagingSenderId: '754296171774',
    projectId: 'kostock-project',
    storageBucket: 'kostock-project.appspot.com',
    iosBundleId: 'com.example.kostock',
  );
}
